apiVersion: smarttuning.ibm.com/v1alpha2
kind: SearchSpace
data: 
  - 
    name: svc-0-mock-configmap
    tunables:
      number:
        - name: "X_VALUE"
          lower:
            value: -10
          upper:
            value: 10
metadata: 
  name: svc-0-mock-searchspace
  namespace: uapp
spec: 
  deployment: svc-0-mock22222
  manifests: 
    - 
      name: svc-0-mock-configmap
      type: configMap
  namespace: uapp
  service: svc-0-mock22222
